on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: echo "This is job 1"
    - run: pwd
    - run: ls
  job2:
    runs-on: windows-latest
    steps:
    - run: echo "This is job 2"
    - run: node --version